Update GCRdionaeaAlerts

diff --git a/GCRdionaeaAlerts b/GCRdionaeaAlerts
--- a/GCRdionaeaAlerts
+++ b/GCRdionaeaAlerts
@@ -1,65 +1,97 @@
-#!/bin/bash
+#!/bin/sh
 ### BEGIN INIT INFO
-# Provides: GCRdionaeaAlerts
-# Required-Start: $network  
-# Required-Stop:  $network  
-# Default-Start:  2 3 4 5 
-# Default-Stop:
-# Short-Description:	GCR enhanced dionaea syslogs utility
+# Provides:          GCRdionaeaAlerts
+# Required-Start:    $local_fs $network $named $time $syslog
+# Required-Stop:     $local_fs $network $named $time $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Description:       GCR enhanced dionaea syslogs utility
 ### END INIT INFO
 
+SCRIPT="python3 /opt/dionaea/bin/GCRdionaeaAlerts.py"
+RUNAS=dionaea
 
-# after placing file into init.d, must run:
-#    sudo update-rc.d gcr-enhanced-log defaults
+PIDFILE=/opt/dionaea/var/GCRdionaeaAlerts.pid
+LOGFILE=/opt/dionaea/var/log/GCRdionaeaAlerts.log
 
-. /lib/lsb/init-functions
+start() {
+  if [ -f $PIDFILE ] && [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE); then
+    echo 'Service already running' >&2
+    return 1
+  fi
+  echo 'Starting service…' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  su -c "$CMD" $RUNAS > "$PIDFILE"
+ # Try with this command line instead of above if not workable
+ # su -s /bin/sh $RUNAS -c "$CMD" > "$PIDFILE"
+ 
+  sleep 2
+  PID=$(cat $PIDFILE)
+    if pgrep -u $RUNAS -f $NAME > /dev/null
+    then
+      echo "$NAME is now running, the PID is $PID"
+    else
+      echo ''
+      echo "Error! Could not start $NAME!"
+    fi
+}
 
-BASEDIR="/opt/dionaea"
-PIDFOLDER="/opt/dionaea/var/"
-PIDFILE=$PIDFOLDER/gcr-enhanced-log.pid
-LOGFILE="/opt/dionaea/var/log/gcr-enhanced-log.log"
-NAME="GCRdionaeaAlerts"
-DAEMON="gcr-enhanced-log"
-USER="nobody"
-GROUP="nobody"
+stop() {
+  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+    echo 'Service not running' >&2
+    return 1
+  fi
+  echo 'Stopping service…' >&2
+  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo 'Service stopped' >&2
+}
 
-if [ ! -d "$PIDFOLDER" ]; then
-  mkdir $PIDFOLDER
-fi
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file was not removed: $LOGFILE" >&2
+    update-rc.d -f $NAME remove
+    rm -fv "$0"
+  fi
+}
 
-case $1 in
+status() {
+    printf "%-50s" "Checking <NAME>..."
+    if [ -f $PIDFILE ] && [ -s $PIDFILE ]; then
+        PID=$(cat $PIDFILE)
+            if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
+                printf "%s\n" "The process appears to be dead but pidfile still exists"
+            else    
+                echo "Running, the PID is $PID"
+            fi
+    else
+        printf "%s\n" "Service not running"
+    fi
+}
+
+
+case "$1" in
   start)
-    cd $BASEDIR
-    start-stop-daemon --start --oknodo —user nobody --name GCRdionaeaAlerts --pidfile $PIDFILE --startas $BASEDIR/bin/GCRdionaeaAlerts.py -- --daemon
-#    python3 /opt/dionaea/bin/GCRdionaeaAlerts.py & > $LOGFILE 2>> $LOGFILE &
-    log_daemon_msg "$DAEMON started ..."
-    log_end_msg 0
-  ;;
+    start
+    ;;
   stop)
-    if [ -e $PIDFILE ]; then
-        kill `cat $PIDFILE`
-        rm $PIDFILE
-        log_daemon_msg "$DAEMON stopped ..."
-        log_end_msg 0
-    else
-        log_daemon_msg "$DAEMON is *NOT* running"
-        log_end_msg 1
-    fi
-  ;;
-  logs)
-    cat $LOGFILE
-  ;;
+    stop
+    ;;
   status)
-    if [ -e $PIDFILE ]; then
-        status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
-    else
-        log_daemon_msg "$DAEMON is not running ..."
-        log_end_msg 0
-    fi
-  ;;
+    status
+    ;;
+  uninstall)
+    uninstall
+    ;;
+  restart)
+    stop
+    start
+    ;;
   *)
-  # For invalid arguments, print the usage message.
-  echo "Usage: $0 {start|stop|logs|status}"
-  exit 2
-  ;;    
+    echo "Usage: $0 {start|stop|status|restart|uninstall}"
 esac
+
